import { useState } from 'react';
import { downloadSource } from '../utils/downloader';

export default function Home() {
    const [isDownloading, setIsDownloading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleDownload = async () => {
        setIsDownloading(true);
        setError(null);
        try {
            await downloadSource();
        } catch (err) {
            console.error("Download failed:", err);
            setError("Failed to download source. See console for details.");
        } finally {
            setIsDownloading(false);
        }
    };

    return (
        <div>
            <h2 className="page-title">SmartTrack: Test Build</h2>
            <div className="card">
                <p style={{marginBottom: '1rem'}}>Welcome to the test build for SmartTrack.</p>
                <p style={{marginBottom: '1.5rem'}}>You can navigate using the icons at the bottom. This entire application is a static site generated by Gemini, ready for deployment on services like GitHub Pages.</p>
                <button className="primary" onClick={handleDownload} disabled={isDownloading}>
                    {isDownloading ? 'Packaging...' : 'Download Source for GitHub'}
                </button>
                {error && <p style={{color: 'red', marginTop: '1rem'}}>{error}</p>}
            </div>
        </div>
    );
}
